# Generated by Django 2.1.3 on 2018-10-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='主机名')),
                ('os', models.CharField(default='', max_length=256, verbose_name='操作系统')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('arch', models.CharField(default='', max_length=32, verbose_name='架构')),
                ('mem', models.BigIntegerField(default=0, verbose_name='内存')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后发现时间')),
            ],
        ),
    ]
