# Generated by Django 2.0.6 on 2018-12-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='p_ip',
            field=models.GenericIPAddressField(default='', verbose_name='p_IP地址'),
        ),
    ]
