# Generated by Django 2.0.6 on 2018-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20181207_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_v',
            field=models.CharField(default='', max_length=256, verbose_name='操作系统版本'),
        ),
    ]
