# Generated by Django 2.0.6 on 2018-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_host_os_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(default='', max_length=256, verbose_name='CPU型号'),
        ),
    ]
