# Generated by Django 2.0.6 on 2018-12-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_host_cpu_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cpu_model',
        ),
    ]
